interface Country {
  code: string;
  name: string;
}

// Nazioni principali
export const mainCountries: Country[] = [
  { code: 'IT', name: 'Italiano' },
  { code: 'EN', name: 'Inglese' },
  { code: 'FR', name: 'Francese' },
  { code: 'ES', name: 'Spagnolo' },
];

// Tutte le altre nazioni
export const otherCountries: Country[] = [
  { code: 'AD', name: 'Andorra' },
  { code: 'AE', name: 'Emirati Arabi Uniti' },
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AG', name: 'Antigua e Barbuda' },
  { code: 'AI', name: 'Anguilla' },
  { code: 'AL', name: 'Albania' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AO', name: 'Angola' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AT', name: 'Austria' },
  { code: 'AU', name: 'Australia' },
  { code: 'AZ', name: 'Azerbaigian' },
  { code: 'BA', name: 'Bosnia ed Erzegovina' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BE', name: 'Belgio' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BH', name: 'Bahrein' },
  { code: 'BI', name: 'Burundi' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BR', name: 'Brasile' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BY', name: 'Bielorussia' },
  { code: 'BZ', name: 'Belize' },
  { code: 'CA', name: 'Canada' },
  { code: 'CD', name: 'Repubblica Democratica del Congo' },
  { code: 'CF', name: 'Repubblica Centrafricana' },
  { code: 'CG', name: 'Congo' },
  { code: 'CH', name: 'Svizzera' },
  { code: 'CI', name: 'Costa d\'Avorio' },
  { code: 'CL', name: 'Cile' },
  { code: 'CM', name: 'Camerun' },
  { code: 'CN', name: 'Cina' },
  { code: 'CO', name: 'Colombia' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CV', name: 'Capo Verde' },
  { code: 'CY', name: 'Cipro' },
  { code: 'CZ', name: 'Repubblica Ceca' },
  { code: 'DJ', name: 'Gibuti' },
  { code: 'DK', name: 'Danimarca' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Repubblica Dominicana' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EE', name: 'Estonia' },
  { code: 'EG', name: 'Egitto' },
  { code: 'EH', name: 'Sahara Occidentale' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'ET', name: 'Etiopia' },
  { code: 'FI', name: 'Finlandia' },
  { code: 'FJ', name: 'Figi' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GB', name: 'Regno Unito' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GE', name: 'Georgia' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GQ', name: 'Guinea Equatoriale' },
  { code: 'GR', name: 'Grecia' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HR', name: 'Croazia' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HU', name: 'Ungheria' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IE', name: 'Irlanda' },
  { code: 'IL', name: 'Israele' },
  { code: 'IN', name: 'India' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IR', name: 'Iran' },
  { code: 'IS', name: 'Islanda' },
  { code: 'JM', name: 'Giamaica' },
  { code: 'JO', name: 'Giordania' },
  { code: 'JP', name: 'Giappone' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KG', name: 'Kirghizistan' },
  { code: 'KH', name: 'Cambogia' },
  { code: 'KM', name: 'Comore' },
  { code: 'KN', name: 'Saint Kitts e Nevis' },
  { code: 'KP', name: 'Corea del Nord' },
  { code: 'KR', name: 'Corea del Sud' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KZ', name: 'Kazakistan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LB', name: 'Libano' },
  { code: 'LC', name: 'Santa Lucia' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LT', name: 'Lituania' },
  { code: 'LU', name: 'Lussemburgo' },
  { code: 'LV', name: 'Lettonia' },
  { code: 'LY', name: 'Libia' },
  { code: 'MA', name: 'Marocco' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MD', name: 'Moldavia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MH', name: 'Isole Marshall' },
  { code: 'MK', name: 'Macedonia del Nord' },
  { code: 'ML', name: 'Mali' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MT', name: 'Malta' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'MV', name: 'Maldive' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MX', name: 'Messico' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MZ', name: 'Mozambico' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NL', name: 'Paesi Bassi' },
  { code: 'NO', name: 'Norvegia' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NZ', name: 'Nuova Zelanda' },
  { code: 'OM', name: 'Oman' },
  { code: 'PA', name: 'Panama' },
  { code: 'PE', name: 'Perù' },
  { code: 'PG', name: 'Papua Nuova Guinea' },
  { code: 'PH', name: 'Filippine' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PL', name: 'Polonia' },
  { code: 'PT', name: 'Portogallo' },
  { code: 'PW', name: 'Palau' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RO', name: 'Romania' },
  { code: 'RS', name: 'Serbia' },
  { code: 'RU', name: 'Russia' },
  { code: 'RW', name: 'Ruanda' },
  { code: 'SA', name: 'Arabia Saudita' },
  { code: 'SB', name: 'Isole Salomone' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SE', name: 'Svezia' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SK', name: 'Slovacchia' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SM', name: 'San Marino' },
  { code: 'SN', name: 'Senegal' },
  { code: 'SO', name: 'Somalia' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SS', name: 'Sud Sudan' },
  { code: 'ST', name: 'São Tomé e Príncipe' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'SY', name: 'Siria' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'TD', name: 'Ciad' },
  { code: 'TG', name: 'Togo' },
  { code: 'TH', name: 'Thailandia' },
  { code: 'TJ', name: 'Tagikistan' },
  { code: 'TL', name: 'Timor Est' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TR', name: 'Turchia' },
  { code: 'TT', name: 'Trinidad e Tobago' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'UA', name: 'Ucraina' },
  { code: 'UG', name: 'Uganda' },
  { code: 'US', name: 'Stati Uniti' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VA', name: 'Città del Vaticano' },
  { code: 'VC', name: 'Saint Vincent e Grenadine' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'WS', name: 'Samoa' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZA', name: 'Sudafrica' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
  { code: 'WLS', name: 'Galles' },
  { code: 'NIR', name: 'Irlanda del Nord' },
  { code: 'SCT', name: 'Scozia' },
];

// Funzione per ottenere il nome del paese dal codice
export const getCountryName = (code: string): string => {
  const mainCountry = mainCountries.find(c => c.code === code);
  if (mainCountry) return mainCountry.name;
  
  const otherCountry = otherCountries.find(c => c.code === code);
  return otherCountry ? otherCountry.name : code;
};

// Lista completa delle nazioni
export const countries = [...mainCountries, ...otherCountries].sort((a, b) => a.name.localeCompare(b.name));
